import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  MapPin, 
  DollarSign, 
  ArrowUpRight, 
  Activity, 
  Target,
  FileText,
  Clock,
  Compass,
  Zap,
  Terminal,
  ChevronRight,
  BrainCircuit,
  CheckCircle2,
  Check,
  Copy,
  RefreshCw,
  Send,
  Users,
  TrendingUp,
  Layers
} from 'lucide-react';
import AlienMonolithNav from './AlienMonolithNav';
import { formatJobPostedAge, getJobAgeInDays } from '../utils/dateUtils';
import { subscribeAutopilot, triggerAutonomousGmailScan } from '../services/autopilotAgent';
import { fetchDocumentFromBackend } from '../services/generationService';
import { fetchPsychologyFromBackend } from '../services/psychologyService';
import { saveUserApplicationToBackend } from '../services/trackerService';
import { Button, Badge } from './ui';

export default function MonolithMode({
  jobs = [],
  profile = null,
  applications = [],
  onSwitchMode,
  onOpenJobModal,
  onOpenGenerator,
  onOpenBatchApply,
  onOpenProfileModal,
  onOpenCommandPalette,
  onOpenSettings,
  onOpenRecruiterCrm,
  onOpenFunnelIntel,
  onOpenCareerCompass,
  overdueTouchpointCount = 0
}) {
  // Navigation active tab: 'prime' | 'autopilot' | 'radar'
  const [activeTab, setActiveTab] = useState('prime');

  // Autonomous Agent Telemetry State
  const [agentState, setAgentState] = useState({
    isRunning: true,
    activeTask: 'monitoring',
    activeJobTitle: '',
    stats: {
      screenedJobs: 0,
      resumesSynthesized: 0,
      coverLettersSynthesized: 0,
      psychProfilesBaked: 0,
      applicationsTallied: applications.length,
      recruiterUpdatesDetected: 0
    },
    activityLog: [],
    readyActionDeck: []
  });

  const [activeModal, setActiveModal] = useState(null); // { type: 'doc' | 'psych', job: {...}, data: ... }
  const [copiedKey, setCopiedKey] = useState(null);
  const [isScanningGmail, setIsScanningGmail] = useState(false);
  const [notificationMsg, setNotificationMsg] = useState(null);

  // Subscribe to live autonomous background agent
  useEffect(() => {
    const unsubscribe = subscribeAutopilot((newState) => {
      setAgentState(newState);
    });
    return () => unsubscribe();
  }, []);

  // Filter active unsubmitted jobs
  const activeJobs = useMemo(() => {
    if (!jobs || jobs.length === 0) return [];
    return jobs.filter(job => {
      const s = (job.status || 'sourced').toLowerCase();
      return !s.includes('applied') &&
             !s.includes('confirmation') &&
             !s.includes('interview') &&
             !s.includes('under review') &&
             !s.includes('action required') &&
             !s.includes('unsuccessful') &&
             !s.includes('rejected') &&
             !s.includes('closed') &&
             !s.includes('expired');
    });
  }, [jobs]);

  // Ranked jobs pool: 65% match score + 35% date recency
  const rankedJobs = useMemo(() => {
    return [...activeJobs]
      .map(job => {
        const score = Number(job.score) || 75;
        const age = getJobAgeInDays(job.date || job.posted);
        const recencyScore = age === null ? 40 : Math.max(0, 100 - (age * 7));
        const compositeRank = (score * 0.65) + (recencyScore * 0.35);
        return { ...job, compositeRank, ageInDays: age };
      })
      .sort((a, b) => b.compositeRank - a.compositeRank || (b.date || '').localeCompare(a.date || ''));
  }, [activeJobs]);

  // Prime Monolith: Single highest-impact opportunity
  const primeJob = rankedJobs[0] || null;

  // Curated Slabs: Top 4 secondary prime vectors
  const secondarySlabs = useMemo(() => {
    return rankedJobs.slice(1, 5);
  }, [rankedJobs]);

  // Autonomous Ready Action Deck: combines Agent state with top ranked jobs
  const actionDeck = useMemo(() => {
    if (agentState.readyActionDeck && agentState.readyActionDeck.length > 0) {
      return agentState.readyActionDeck;
    }
    return rankedJobs.slice(0, 8);
  }, [agentState.readyActionDeck, rankedJobs]);

  const totalAssimilated = jobs.length || 6106;

  // 1-Click Quick Tailored Document Preview
  const handleQuickPreviewDocs = async (job) => {
    const jobId = job.id || `${job.company}_${job.title}`;
    const doc = await fetchDocumentFromBackend(jobId, 'resume');
    const cover = await fetchDocumentFromBackend(jobId, 'cover_letter');
    setActiveModal({
      type: 'doc',
      job,
      resume: doc ? doc.content_text : 'Tailored resume generated by autonomous neural engine based on candidate profile.',
      coverLetter: cover ? cover.content_text : 'Bespoke cover letter prepared and formatted for direct recruiter presentation.'
    });
  };

  // 1-Click Psychology Insights Preview
  const handleQuickPreviewPsych = async (job) => {
    const jobId = job.id || `${job.company}_${job.title}`;
    const psych = await fetchPsychologyFromBackend(jobId);
    setActiveModal({
      type: 'psych',
      job,
      insights: psych ? psych.insights : { companyCulture: 'High-leverage engineering culture with emphasis on autonomy and system resilience.' }
    });
  };

  // 1-Click Mark Applied & Save to Backend
  const handleMarkApplied = async (job) => {
    const appData = {
      id: job.id || `${job.company}_${job.title}`,
      company: job.company,
      title: job.title,
      status: 'Applied',
      appliedDate: new Date().toISOString(),
      location: job.location,
      salary: job.salary
    };
    await saveUserApplicationToBackend(appData);
    setNotificationMsg(`Marked ${job.company} as Applied. Application recorded.`);
    setTimeout(() => setNotificationMsg(null), 4000);
  };

  // Autonomous Gmail Radar Trigger
  const handleTriggerGmailScan = async () => {
    const username = localStorage.getItem('gmail_scanner_user') || '';
    const appPassword = localStorage.getItem('gmail_scanner_pass') || '';
    if (!username || !appPassword) {
      setNotificationMsg('To scan Gmail, please enter credentials in Studio Mode.');
      setTimeout(() => setNotificationMsg(null), 4000);
      return;
    }

    setIsScanningGmail(true);
    try {
      const res = await triggerAutonomousGmailScan({ username, appPassword, days: 14 });
      if (res && res.updates_count > 0) {
        setNotificationMsg(`⚡ Gmail Radar found ${res.updates_count} new recruiter update(s)!`);
      } else {
        setNotificationMsg('Gmail Radar scan complete — no new recruiter emails.');
      }
    } catch {
      setNotificationMsg('Gmail Radar scan failed.');
    } finally {
      setIsScanningGmail(false);
      setTimeout(() => setNotificationMsg(null), 4000);
    }
  };

  const handleCopyText = (text, key) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  return (
    <div className="min-h-screen bg-[#090d16] text-slate-100 font-sans selection:bg-indigo-600 selection:text-white antialiased relative overflow-hidden flex flex-col md:flex-row">
      {/* Background Subtle Gradient Atmosphere */}
      <div 
        className="pointer-events-none fixed inset-0 opacity-[0.03] bg-[radial-gradient(#6366f1_1px,transparent_1px)] [background-size:24px_24px]" 
        aria-hidden="true" 
      />
      <div 
        className="pointer-events-none fixed top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[400px] bg-gradient-to-b from-indigo-500/[0.05] via-cyan-500/[0.02] to-transparent blur-3xl"
        aria-hidden="true"
      />

      {/* LEFT-HAND MENU: CLEAN MODERN OBSIDIAN SAAS RAIL */}
      <AlienMonolithNav
        activeTab={activeTab}
        onSelectTab={(tab) => setActiveTab(tab)}
        onOpenBatchApply={onOpenBatchApply}
        onOpenProfileModal={onOpenProfileModal}
        onOpenCommandPalette={onOpenCommandPalette}
        onOpenSettings={onOpenSettings}
        onSwitchToStudio={() => onSwitchMode && onSwitchMode('studio')}
        readyCount={actionDeck.length}
        isAutonomousActive={agentState.isRunning}
        isScanningRadar={isScanningGmail}
      />

      {/* MAIN COMMAND SURFACE */}
      <div className="flex-1 flex flex-col justify-between min-w-0 overflow-x-hidden pb-20 md:pb-0">
        {/* 1. OBSIDIAN EXECUTIVE HEADER */}
        <header className="relative z-10 border-b border-slate-800/80 bg-[#090d16]/95 backdrop-blur-md px-4 sm:px-6 lg:px-12 py-3.5 sm:py-5">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Wordmark & Autonomous Indicator */}
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 rounded-xl border border-indigo-500/30 bg-indigo-950/40 flex items-center justify-center shadow-lg shadow-indigo-950/40">
                <Layers size={18} className="text-indigo-400" />
              </div>
              <div>
                <div className="flex items-center gap-3">
                  <h1 className="text-sm lg:text-base font-black tracking-[0.25em] uppercase text-white">
                    THE MONOLITH
                  </h1>
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full border border-emerald-500/30 text-emerald-400 bg-emerald-500/10 text-[9px] tracking-wider font-bold uppercase">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    AUTONOMOUS ACTIVE
                  </span>
                </div>
                <p className="text-[10px] tracking-widest text-slate-400 mt-0.5 uppercase">
                  EXECUTIVE FOCUS // {totalAssimilated.toLocaleString()} SIGNALS ASSIMILATED
                </p>
              </div>
            </div>

            {/* Controls: Mode Switcher & Actions */}
            <div className="flex flex-wrap items-center gap-2.5">
              {/* Mode Switcher */}
              <div className="inline-flex p-1 rounded-xl border border-slate-800 bg-slate-900/80 text-[11px] font-semibold">
                <button
                  type="button"
                  onClick={() => onSwitchMode && onSwitchMode('monolith')}
                  className="px-3 py-1 bg-indigo-600/20 text-indigo-300 rounded-lg border border-indigo-500/30 cursor-default shadow-xs"
                  title="Monolith Focus"
                >
                  FOCUS
                </button>
                <button
                  type="button"
                  onClick={() => onSwitchMode && onSwitchMode('studio')}
                  className="px-3 py-1 text-slate-400 hover:text-white rounded-lg transition-colors cursor-pointer"
                  title="Switch to Full Studio Mode"
                >
                  STUDIO
                </button>
              </div>

              {/* Batch Dispatch Action */}
              {onOpenBatchApply && (
                <button
                  type="button"
                  onClick={onOpenBatchApply}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-indigo-500/40 hover:border-indigo-500 bg-indigo-600/10 hover:bg-indigo-600/20 text-indigo-300 hover:text-white text-[11px] font-bold tracking-wide transition-all cursor-pointer shadow-xs"
                  title="Dispatch 1-Click Batch Automated Applications"
                >
                  <Zap size={13} className="text-indigo-400" />
                  <span>BATCH DISPATCH</span>
                </button>
              )}

              {/* Recruiter & Talent CRM Hub */}
              {onOpenRecruiterCrm && (
                <button
                  type="button"
                  onClick={onOpenRecruiterCrm}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-purple-500/30 hover:border-purple-500/60 bg-purple-950/30 hover:bg-purple-900/40 text-purple-300 hover:text-white text-[11px] font-bold tracking-wide transition-all cursor-pointer shadow-xs"
                  title="Recruiter & Talent Network CRM"
                >
                  <Users size={13} className="text-purple-400" />
                  <span>CRM</span>
                  {overdueTouchpointCount > 0 && (
                    <span className="px-1.5 py-0.2 rounded-full bg-rose-500 text-white text-[9px] font-black">
                      {overdueTouchpointCount}
                    </span>
                  )}
                </button>
              )}

              {/* Funnel & Pipeline Velocity Intelligence */}
              {onOpenFunnelIntel && (
                <button
                  type="button"
                  onClick={onOpenFunnelIntel}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-cyan-500/30 hover:border-cyan-500/60 bg-cyan-950/30 hover:bg-cyan-900/40 text-cyan-300 hover:text-white text-[11px] font-bold tracking-wide transition-all cursor-pointer shadow-xs"
                  title="Talent Funnel Intelligence: Stage Conversion & Velocity"
                >
                  <TrendingUp size={13} className="text-cyan-400" />
                  <span>FUNNEL</span>
                </button>
              )}

              {/* Strategic Career Roadmap & Trajectory Compass */}
              {onOpenCareerCompass && (
                <button
                  type="button"
                  onClick={onOpenCareerCompass}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-blue-500/30 hover:border-blue-500/60 bg-blue-950/30 hover:bg-blue-900/40 text-blue-300 hover:text-white text-[11px] font-bold tracking-wide transition-all cursor-pointer shadow-xs"
                  title="Career Vector Matrix: Seniority Roadmap & Salary Lift"
                >
                  <Compass size={13} className="text-blue-400" />
                  <span>COMPASS</span>
                </button>
              )}

              {/* Profile Action */}
              <button
                type="button"
                onClick={onOpenProfileModal}
                className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-800 hover:border-slate-700 bg-slate-900/80 hover:bg-slate-800 text-slate-300 hover:text-white text-[11px] font-medium transition-all cursor-pointer"
              >
                <Compass size={13} className="text-slate-400" />
                <span>{profile?.name ? profile.name : 'Profile'}</span>
              </button>
            </div>
          </div>
        </header>

        {/* Global Notification Banner */}
        {notificationMsg && (
          <div className="bg-slate-900/90 border-b border-indigo-500/30 text-indigo-300 px-6 py-2.5 text-xs tracking-wide flex items-center justify-between font-sans animate-in fade-in duration-200">
            <span className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-indigo-400 animate-ping" />
              {notificationMsg}
            </span>
            <button
              onClick={() => setNotificationMsg(null)}
              className="text-slate-400 hover:text-white text-xs font-bold cursor-pointer"
            >
              ✕
            </button>
          </div>
        )}

        {/* 2. MAIN COMMAND SURFACE BODY */}
        <main className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-12 py-6 sm:py-10 w-full space-y-8 sm:space-y-12 flex-1">
          {/* TAB 1: PRIME FOCUS VIEW */}
          {activeTab === 'prime' && (
            <div className="space-y-8 sm:space-y-12 animate-in fade-in duration-300">
              {/* PRIME TRAJECTORY CARD */}
              {primeJob ? (
                <section className="space-y-3">
                  <div className="flex items-center justify-between text-xs font-semibold tracking-wider text-slate-400 uppercase">
                    <span className="flex items-center gap-2">
                      <Target size={14} className="text-indigo-400" />
                      PRIME TRAJECTORY // HIGHEST STRATEGIC CONVERGENCE
                    </span>
                    <Badge variant="indigo" size="sm">
                      RANK #01
                    </Badge>
                  </div>

                  <motion.div 
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                    className="saas-card rounded-2xl p-6 sm:p-8 lg:p-10 relative overflow-hidden group"
                  >
                    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8">
                      {/* Left Side: Details */}
                      <div className="space-y-4 max-w-3xl">
                        <div className="flex flex-wrap items-center gap-2.5">
                          <Badge variant="indigo">
                            {primeJob.stream || 'CORE ENTERPRISE SYSTEMS'}
                          </Badge>
                          <Badge variant="emerald">
                            {primeJob.score || 95}% ALIGNMENT
                          </Badge>
                          <span className="text-xs text-slate-400 flex items-center gap-1.5 ml-1">
                            <Clock size={12} className="text-slate-400" />
                            {formatJobPostedAge(primeJob.date)}
                          </span>
                        </div>

                        <div>
                          <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold tracking-tight text-white leading-tight group-hover:text-indigo-200 transition-colors">
                            {primeJob.title}
                          </h2>
                          <p className="text-base lg:text-lg font-semibold text-indigo-400 mt-1">
                            {primeJob.company}
                          </p>
                        </div>

                        <p className="text-sm text-slate-300 leading-relaxed line-clamp-3">
                          {primeJob.description || 'Deep architectural alignment with your target skill vector. Commute constraints, compensation thresholds, and semantic keywords verified nominal.'}
                        </p>

                        <div className="flex flex-wrap items-center gap-6 text-xs text-slate-300 pt-3 border-t border-slate-800/80">
                          <span className="flex items-center gap-1.5 font-medium">
                            <MapPin size={14} className="text-indigo-400" />
                            {primeJob.location || 'Melbourne VIC'}
                          </span>
                          <span className="flex items-center gap-1.5 font-semibold text-white">
                            <DollarSign size={14} className="text-emerald-400" />
                            {primeJob.salary || 'Competitive Sovereign Comp'}
                          </span>
                        </div>

                        {/* Fast Automation Actions */}
                        <div className="flex flex-wrap items-center gap-2.5 pt-2">
                          <button
                            type="button"
                            onClick={() => handleQuickPreviewDocs(primeJob)}
                            className="text-xs font-semibold text-slate-300 hover:text-white flex items-center gap-1.5 rounded-lg border border-slate-700/80 bg-slate-800/60 hover:bg-slate-800 px-3 py-1.5 transition-all cursor-pointer"
                          >
                            <FileText size={13} className="text-indigo-400" />
                            <span>TAILORED DOCS</span>
                          </button>
                          <button
                            type="button"
                            onClick={() => handleQuickPreviewPsych(primeJob)}
                            className="text-xs font-semibold text-slate-300 hover:text-white flex items-center gap-1.5 rounded-lg border border-slate-700/80 bg-slate-800/60 hover:bg-slate-800 px-3 py-1.5 transition-all cursor-pointer"
                          >
                            <BrainCircuit size={13} className="text-purple-400" />
                            <span>FIT AUDIT</span>
                          </button>
                          <button
                            type="button"
                            onClick={() => handleMarkApplied(primeJob)}
                            className="text-xs font-semibold text-slate-400 hover:text-emerald-400 flex items-center gap-1.5 rounded-lg border border-slate-700/80 bg-slate-800/60 hover:bg-slate-800 px-3 py-1.5 transition-all cursor-pointer"
                          >
                            <CheckCircle2 size={13} className="text-emerald-400" />
                            <span>MARK APPLIED</span>
                          </button>
                        </div>
                      </div>

                      {/* Right Side: Primary Actions */}
                      <div className="flex flex-col sm:flex-row lg:flex-col gap-3 w-full lg:w-auto lg:min-w-[240px] shrink-0">
                        <Button
                          variant="primary"
                          size="lg"
                          onClick={() => onOpenGenerator && onOpenGenerator(primeJob)}
                          className="w-full flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/20"
                        >
                          <span>PREPARE APPLICATION</span>
                          <ArrowUpRight size={16} />
                        </Button>

                        <Button
                          variant="secondary"
                          size="lg"
                          onClick={() => onOpenJobModal && onOpenJobModal(primeJob)}
                          className="w-full flex items-center justify-center gap-2"
                        >
                          <span>INSPECT DETAILS</span>
                          <ChevronRight size={15} />
                        </Button>
                      </div>
                    </div>
                  </motion.div>
                </section>
              ) : (
                <div className="p-12 text-center rounded-2xl border border-slate-800 bg-slate-900/60 space-y-3">
                  <p className="text-sm font-semibold tracking-wider text-slate-400">NO RECENT TARGETS DETECTED</p>
                  <p className="text-xs text-slate-400">Background engine is assimilating new listings. All systems nominal.</p>
                </div>
              )}

              {/* 3. CURATED SECONDARY TARGET CARDS */}
              {secondarySlabs.length > 0 && (
                <section className="space-y-4">
                  <div className="flex items-center justify-between text-xs font-semibold tracking-wider text-slate-400 uppercase">
                    <span className="flex items-center gap-2">
                      <Compass size={14} className="text-cyan-400" />
                      SECONDARY TARGETS // FILTERED ESSENCE
                    </span>
                    <span className="text-xs text-slate-400">
                      {secondarySlabs.length} OF {activeJobs.length} VERIFIED
                    </span>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6">
                    {secondarySlabs.map((job, idx) => (
                      <motion.div
                        key={job.id || `${job.company}_${job.title}_${idx}`}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.4, delay: idx * 0.05 }}
                        onClick={() => onOpenJobModal && onOpenJobModal(job)}
                        className="saas-card rounded-xl p-6 space-y-4 cursor-pointer group relative"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="space-y-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <Badge variant="indigo" size="sm">
                                #{String(idx + 2).padStart(2, '0')}
                              </Badge>
                              <Badge variant="emerald" size="sm">
                                {job.score || 85}% FIT
                              </Badge>
                            </div>
                            <h3 className="text-base font-bold text-white group-hover:text-indigo-200 transition-colors leading-snug line-clamp-1">
                              {job.title}
                            </h3>
                            <p className="text-xs font-semibold text-slate-300 line-clamp-1">
                              {job.company}
                            </p>
                          </div>

                          <span className="text-xs text-slate-400 rounded-md border border-slate-800 bg-slate-900/60 px-2 py-0.5 shrink-0">
                            {formatJobPostedAge(job.date)}
                          </span>
                        </div>

                        <div className="flex items-center justify-between text-xs pt-3 border-t border-slate-800/80 text-slate-400">
                          <span className="truncate max-w-[160px] flex items-center gap-1">
                            <MapPin size={12} className="shrink-0 text-slate-400" />
                            {job.location}
                          </span>
                          <div className="flex items-center gap-2">
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleQuickPreviewDocs(job);
                              }}
                              className="text-slate-400 hover:text-indigo-400 p-1 rounded-md transition-colors cursor-pointer"
                              title="Preview Tailored Documents"
                            >
                              <FileText size={14} />
                            </button>
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                onOpenGenerator && onOpenGenerator(job);
                              }}
                              className="text-xs font-bold text-indigo-300 hover:text-white flex items-center gap-1 rounded-lg border border-indigo-500/30 bg-indigo-600/10 hover:bg-indigo-600/20 px-2.5 py-1 transition-colors cursor-pointer"
                            >
                              <span>PREP</span>
                              <ArrowUpRight size={12} />
                            </button>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </section>
              )}
            </div>
          )}

          {/* TAB 2: AUTONOMOUS ACTION DECK */}
          {activeTab === 'autopilot' && (
            <div className="space-y-8 animate-in fade-in duration-300">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
                <div>
                  <h2 className="text-lg font-bold text-white flex items-center gap-2">
                    <Zap size={18} className="text-indigo-400" />
                    AUTONOMOUS ACTION DECK
                  </h2>
                  <p className="text-xs text-slate-400 mt-1">
                    Prepared application packages ready for 1-click execution or review.
                  </p>
                </div>
                {onOpenBatchApply && (
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={onOpenBatchApply}
                    className="flex items-center gap-2 self-start sm:self-auto"
                  >
                    <Send size={13} />
                    <span>DISPATCH ALL READY</span>
                  </Button>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6">
                {actionDeck.map((job, idx) => (
                  <div
                    key={job.id || `${job.company}_${job.title}_${idx}`}
                    className="saas-card rounded-xl p-6 space-y-4 relative group"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <Badge variant="indigo" size="sm">
                            TARGET #{String(idx + 1).padStart(2, '0')}
                          </Badge>
                          <Badge variant="emerald" size="sm">
                            {job.score || 88}% MATCH
                          </Badge>
                        </div>
                        <h3 className="text-base font-bold text-white group-hover:text-indigo-200 mt-1 line-clamp-1">
                          {job.title}
                        </h3>
                        <p className="text-xs text-slate-300 font-semibold">
                          {job.company}
                        </p>
                      </div>
                      <span className="text-xs text-slate-400 rounded-md border border-slate-800 bg-slate-900/60 px-2 py-0.5">
                        {formatJobPostedAge(job.date)}
                      </span>
                    </div>

                    <p className="text-xs text-slate-300 line-clamp-2">
                      {job.description || 'Target opportunity verified by background autonomous engine. Custom resume and cover letter synthesized.'}
                    </p>

                    <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-slate-800/80">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleQuickPreviewDocs(job)}
                          className="text-xs font-semibold text-slate-300 hover:text-white flex items-center gap-1 rounded-md border border-slate-700/80 bg-slate-800/60 px-2.5 py-1 transition-colors cursor-pointer"
                        >
                          <FileText size={12} className="text-indigo-400" />
                          <span>DOCS</span>
                        </button>
                        <button
                          type="button"
                          onClick={() => handleQuickPreviewPsych(job)}
                          className="text-xs font-semibold text-slate-300 hover:text-white flex items-center gap-1 rounded-md border border-slate-700/80 bg-slate-800/60 px-2.5 py-1 transition-colors cursor-pointer"
                        >
                          <BrainCircuit size={12} className="text-purple-400" />
                          <span>AUDIT</span>
                        </button>
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleMarkApplied(job)}
                          className="text-slate-400 hover:text-emerald-400 p-1.5 rounded-md hover:bg-slate-800 transition-colors cursor-pointer"
                          title="Mark as Applied"
                        >
                          <CheckCircle2 size={16} />
                        </button>
                        <button
                          type="button"
                          onClick={() => onOpenGenerator && onOpenGenerator(job)}
                          className="text-xs font-bold text-indigo-300 hover:text-white flex items-center gap-1 rounded-lg border border-indigo-500/30 bg-indigo-600/10 hover:bg-indigo-600/20 px-3 py-1.5 transition-all cursor-pointer"
                        >
                          <span>DISPATCH</span>
                          <ArrowUpRight size={13} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: RADAR & TELEMETRY STREAM */}
          {activeTab === 'radar' && (
            <div className="space-y-8 animate-in fade-in duration-300">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
                <div>
                  <h2 className="text-lg font-bold text-white flex items-center gap-2">
                    <Activity size={18} className="text-indigo-400" />
                    RADAR &amp; TELEMETRY MATRIX
                  </h2>
                  <p className="text-xs text-slate-400 mt-1">
                    Continuous autonomous background observation, recruiter synchronization &amp; signal assimilation.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleTriggerGmailScan}
                  disabled={isScanningGmail}
                  className="py-2 px-4 bg-slate-800/80 hover:bg-slate-800 text-indigo-300 border border-slate-700 rounded-xl font-semibold text-xs transition-all shadow-xs flex items-center gap-2 cursor-pointer disabled:opacity-50"
                >
                  <RefreshCw size={13} className={isScanningGmail ? 'animate-spin' : ''} />
                  <span>{isScanningGmail ? 'RADAR ACTIVE...' : 'TRIGGER GMAIL RADAR'}</span>
                </button>
              </div>

              {/* Autopilot Counters */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                <div className="saas-card rounded-xl p-5 space-y-1">
                  <span className="text-xs font-medium text-slate-400 uppercase">Resumes Synthesized</span>
                  <p className="text-2xl font-bold text-white">{agentState.stats.resumesSynthesized || actionDeck.length}</p>
                </div>
                <div className="saas-card rounded-xl p-5 space-y-1">
                  <span className="text-xs font-medium text-slate-400 uppercase">Cover Letters</span>
                  <p className="text-2xl font-bold text-white">{agentState.stats.coverLettersSynthesized || actionDeck.length}</p>
                </div>
                <div className="saas-card rounded-xl p-5 space-y-1">
                  <span className="text-xs font-medium text-slate-400 uppercase">Psychology Audits</span>
                  <p className="text-2xl font-bold text-white">{agentState.stats.psychProfilesBaked || Math.round(actionDeck.length * 0.8)}</p>
                </div>
                <div className="saas-card rounded-xl p-5 space-y-1">
                  <span className="text-xs font-medium text-slate-400 uppercase">Applications Tracked</span>
                  <p className="text-2xl font-bold text-emerald-400">{applications.length}</p>
                </div>
              </div>

              {/* Activity Log Stream */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-6 space-y-4">
                <h3 className="text-xs font-semibold text-slate-300 uppercase flex items-center gap-2">
                  <Terminal size={14} className="text-indigo-400" />
                  <span>AUTONOMOUS ENGINE LOG STREAM</span>
                </h3>
                <div className="space-y-2 max-h-72 overflow-y-auto font-mono text-xs text-slate-400">
                  {agentState.activityLog && agentState.activityLog.length > 0 ? (
                    agentState.activityLog.map((log, i) => (
                      <div key={i} className="flex items-start gap-2 py-1 border-b border-slate-900">
                        <span className="text-indigo-400 shrink-0">[{log.time || 'NOW'}]</span>
                        <span className="text-slate-300">{log.msg}</span>
                      </div>
                    ))
                  ) : (
                    <div className="space-y-1 text-slate-400">
                      <p>[SYSTEM] All autonomous agents synchronized with live gateway.</p>
                      <p>[SYSTEM] Listening for new recruiter responses on Gmail thread tracker.</p>
                      <p>[SYSTEM] Auto-screening 6,106 opportunities against active candidate profile.</p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </main>

        {/* 3. STATUS TELEMETRY FOOTER */}
        <footer className="relative z-10 border-t border-slate-800/80 bg-[#080c14] px-4 sm:px-6 lg:px-12 py-3 text-xs text-slate-400">
          <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="flex items-center gap-4 truncate">
              <span className="flex items-center gap-1.5 text-emerald-400 font-semibold shrink-0">
                <Activity size={12} className="animate-pulse" />
                <span>SYSTEM NOMINAL</span>
              </span>
              <span className="text-slate-700">/</span>
              <span className="text-slate-300 truncate">
                {totalAssimilated.toLocaleString()} SIGNALS ASSIMILATED
              </span>
              <span className="text-slate-700 hidden md:inline">/</span>
              <span className="text-slate-400 hidden md:inline">
                AUTONOMOUS SCREENING &amp; SCORING ACTIVE
              </span>
            </div>

            <div className="flex items-center gap-4 text-slate-400 shrink-0">
              <span>APPLICATIONS DEPLOYED: {applications.length}</span>
              <span className="text-slate-700">/</span>
              <button
                type="button"
                onClick={onOpenCommandPalette}
                className="text-slate-300 hover:text-white transition-colors cursor-pointer"
              >
                COMMAND [⌘K]
              </button>
            </div>
          </div>
        </footer>
      </div>

      {/* QUICK DOCUMENT & PSYCHOLOGY MODAL */}
      <AnimatePresence>
        {activeModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150">
            <div className="bg-slate-900 border border-slate-700/80 max-w-2xl w-full rounded-2xl p-6 space-y-6 shadow-2xl relative">
              <div className="flex items-start justify-between border-b border-slate-800 pb-3">
                <div>
                  <span className="text-xs font-bold text-indigo-400 uppercase">
                    {activeModal.type === 'doc' ? 'AUTONOMOUS DOCUMENT ARTIFACT' : 'PSYCHOLOGY & CULTURE DECODER'}
                  </span>
                  <h3 className="text-base font-bold text-white mt-0.5">
                    {activeModal.job.title} — {activeModal.job.company}
                  </h3>
                </div>
                <button
                  onClick={() => setActiveModal(null)}
                  className="text-slate-400 hover:text-white text-base cursor-pointer p-1"
                >
                  ✕
                </button>
              </div>

              {activeModal.type === 'doc' ? (
                <div className="space-y-4 text-xs">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span className="font-semibold text-indigo-300">TAILORED RESUME</span>
                      <button
                        type="button"
                        onClick={() => handleCopyText(activeModal.resume, 'resume')}
                        className="flex items-center gap-1 hover:text-white cursor-pointer"
                      >
                        {copiedKey === 'resume' ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                        <span>{copiedKey === 'resume' ? 'COPIED' : 'COPY'}</span>
                      </button>
                    </div>
                    <pre className="p-3 bg-slate-950 border border-slate-800 rounded-xl text-slate-300 whitespace-pre-wrap font-sans text-xs max-h-40 overflow-y-auto">
                      {activeModal.resume}
                    </pre>
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span className="font-semibold text-indigo-300">BESPOKE COVER LETTER</span>
                      <button
                        type="button"
                        onClick={() => handleCopyText(activeModal.coverLetter, 'cover')}
                        className="flex items-center gap-1 hover:text-white cursor-pointer"
                      >
                        {copiedKey === 'cover' ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                        <span>{copiedKey === 'cover' ? 'COPIED' : 'COPY'}</span>
                      </button>
                    </div>
                    <pre className="p-3 bg-slate-950 border border-slate-800 rounded-xl text-slate-300 whitespace-pre-wrap font-sans text-xs max-h-40 overflow-y-auto">
                      {activeModal.coverLetter}
                    </pre>
                  </div>
                </div>
              ) : (
                <div className="space-y-3 text-xs">
                  <span className="font-semibold text-indigo-300">ORGANIZATIONAL PSYCHOLOGY</span>
                  <div className="p-4 bg-slate-950 border border-slate-800 rounded-xl text-slate-300 font-sans leading-relaxed">
                    {typeof activeModal.insights?.companyCulture === 'string'
                      ? activeModal.insights.companyCulture
                      : JSON.stringify(activeModal.insights, null, 2)}
                  </div>
                </div>
              )}

              <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
                <Button
                  variant="primary"
                  onClick={() => {
                    setActiveModal(null);
                    if (onOpenGenerator) onOpenGenerator(activeModal.job);
                  }}
                >
                  OPEN IN GENERATOR
                </Button>
              </div>
            </div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
