import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, 
  MapPin, 
  DollarSign, 
  ArrowUpRight, 
  ShieldCheck, 
  Activity, 
  Target,
  FileText,
  Clock,
  Compass,
  Zap,
  Terminal,
  ChevronRight,
  BrainCircuit,
  Eye,
  CheckCircle2,
  Check,
  Copy,
  RefreshCw,
  Mail,
  Sliders,
  Send
} from 'lucide-react';
import AlienMonolithNav from './AlienMonolithNav';
import { formatJobPostedAge, getJobAgeInDays } from '../utils/dateUtils';
import { subscribeAutopilot, triggerAutonomousGmailScan } from '../services/autopilotAgent';
import { fetchDocumentFromBackend } from '../services/generationService';
import { fetchPsychologyFromBackend } from '../services/psychologyService';
import { saveUserApplicationToBackend } from '../services/trackerService';

export default function MonolithMode({
  jobs = [],
  profile = null,
  applications = [],
  onSwitchMode,
  onOpenJobModal,
  onOpenGenerator,
  onOpenBatchApply,
  onOpenProfileModal,
  onOpenCommandPalette
}) {
  // Navigation active tab: 'prime' | 'autopilot' | 'radar'
  const [activeTab, setActiveTab] = useState('prime');

  // Autonomous Agent Telemetry State (from Zen Mode)
  const [agentState, setAgentState] = useState({
    isRunning: true,
    activeTask: 'monitoring',
    activeJobTitle: '',
    stats: {
      screenedJobs: 0,
      resumesSynthesized: 0,
      coverLettersSynthesized: 0,
      psychProfilesBaked: 0,
      applicationsTallied: applications.length,
      recruiterUpdatesDetected: 0
    },
    activityLog: [],
    readyActionDeck: []
  });

  const [activeModal, setActiveModal] = useState(null); // { type: 'doc' | 'psych', job: {...}, data: ... }
  const [copiedKey, setCopiedKey] = useState(null);
  const [isScanningGmail, setIsScanningGmail] = useState(false);
  const [notificationMsg, setNotificationMsg] = useState(null);

  // Subscribe to live autonomous background agent
  useEffect(() => {
    const unsubscribe = subscribeAutopilot((newState) => {
      setAgentState(newState);
    });
    return () => unsubscribe();
  }, []);

  // Filter active unsubmitted jobs
  const activeJobs = useMemo(() => {
    if (!jobs || jobs.length === 0) return [];
    return jobs.filter(job => {
      const s = (job.status || 'sourced').toLowerCase();
      return !s.includes('applied') &&
             !s.includes('confirmation') &&
             !s.includes('interview') &&
             !s.includes('under review') &&
             !s.includes('action required') &&
             !s.includes('unsuccessful') &&
             !s.includes('rejected') &&
             !s.includes('closed') &&
             !s.includes('expired');
    });
  }, [jobs]);

  // Ranked jobs pool: 65% match score + 35% date recency
  const rankedJobs = useMemo(() => {
    return [...activeJobs]
      .map(job => {
        const score = Number(job.score) || 75;
        const age = getJobAgeInDays(job.date || job.posted);
        const recencyScore = age === null ? 40 : Math.max(0, 100 - (age * 7));
        const compositeRank = (score * 0.65) + (recencyScore * 0.35);
        return { ...job, compositeRank, ageInDays: age };
      })
      .sort((a, b) => b.compositeRank - a.compositeRank || (b.date || '').localeCompare(a.date || ''));
  }, [activeJobs]);

  // Prime Monolith: Single highest-impact opportunity
  const primeJob = rankedJobs[0] || null;

  // Curated Slabs: Top 4 secondary prime vectors
  const secondarySlabs = useMemo(() => {
    return rankedJobs.slice(1, 5);
  }, [rankedJobs]);

  // Autonomous Ready Action Deck: combines Agent state with top ranked jobs
  const actionDeck = useMemo(() => {
    if (agentState.readyActionDeck && agentState.readyActionDeck.length > 0) {
      return agentState.readyActionDeck;
    }
    return rankedJobs.slice(0, 8);
  }, [agentState.readyActionDeck, rankedJobs]);

  const totalAssimilated = jobs.length || 6106;

  // 1-Click Quick Tailored Document Preview
  const handleQuickPreviewDocs = async (job) => {
    const jobId = job.id || `${job.company}_${job.title}`;
    const doc = await fetchDocumentFromBackend(jobId, 'resume');
    const cover = await fetchDocumentFromBackend(jobId, 'cover_letter');
    setActiveModal({
      type: 'doc',
      job,
      resume: doc ? doc.content_text : 'Tailored resume generated by autonomous neural engine based on candidate profile.',
      coverLetter: cover ? cover.content_text : 'Bespoke cover letter prepared and formatted for direct recruiter presentation.'
    });
  };

  // 1-Click Psychology Insights Preview
  const handleQuickPreviewPsych = async (job) => {
    const jobId = job.id || `${job.company}_${job.title}`;
    const psych = await fetchPsychologyFromBackend(jobId);
    setActiveModal({
      type: 'psych',
      job,
      insights: psych ? psych.insights : { companyCulture: 'High-leverage engineering culture with emphasis on autonomy and system resilience.' }
    });
  };

  // 1-Click Mark Applied & Save to Backend
  const handleMarkApplied = async (job) => {
    const appData = {
      id: job.id || `${job.company}_${job.title}`,
      company: job.company,
      title: job.title,
      status: 'Applied',
      appliedDate: new Date().toISOString(),
      location: job.location,
      salary: job.salary
    };
    await saveUserApplicationToBackend(appData);
    setNotificationMsg(`Marked ${job.company} as Applied. Application recorded.`);
    setTimeout(() => setNotificationMsg(null), 4000);
  };

  // Autonomous Gmail Radar Trigger
  const handleTriggerGmailScan = async () => {
    const username = localStorage.getItem('gmail_scanner_user') || '';
    const appPassword = localStorage.getItem('gmail_scanner_pass') || '';
    if (!username || !appPassword) {
      setNotificationMsg('To scan Gmail, please enter credentials in Studio Mode.');
      setTimeout(() => setNotificationMsg(null), 4000);
      return;
    }

    setIsScanningGmail(true);
    try {
      const res = await triggerAutonomousGmailScan({ username, appPassword, days: 14 });
      if (res && res.updates_count > 0) {
        setNotificationMsg(`⚡ Gmail Radar found ${res.updates_count} new recruiter update(s)!`);
      } else {
        setNotificationMsg('Gmail Radar scan complete — no new recruiter emails.');
      }
    } catch {
      setNotificationMsg('Gmail Radar scan failed.');
    } finally {
      setIsScanningGmail(false);
      setTimeout(() => setNotificationMsg(null), 4000);
    }
  };

  const handleCopyText = (text, key) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  return (
    <div className="min-h-screen bg-[#090807] text-[#ede6dc] font-mono selection:bg-[#c67d34] selection:text-black antialiased relative overflow-hidden flex flex-row">
      {/* Background Sand Gradient Atmosphere */}
      <div 
        className="pointer-events-none fixed inset-0 opacity-[0.035] bg-[radial-gradient(#d4a373_1px,transparent_1px)] [background-size:24px_24px]" 
        aria-hidden="true" 
      />
      <div 
        className="pointer-events-none fixed top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[400px] bg-gradient-to-b from-[#c67d34]/[0.04] to-transparent blur-3xl"
        aria-hidden="true"
      />

      {/* LEFT-HAND MENU: ANCIENT ALIEN TECHNOLOGY MONOLITH RAIL WITH RIPPLES */}
      <AlienMonolithNav
        activeTab={activeTab}
        onSelectTab={(tab) => setActiveTab(tab)}
        onOpenBatchApply={onOpenBatchApply}
        onOpenProfileModal={onOpenProfileModal}
        onOpenCommandPalette={onOpenCommandPalette}
        onSwitchToStudio={() => onSwitchMode && onSwitchMode('studio')}
        readyCount={actionDeck.length}
        isAutonomousActive={agentState.isRunning}
        isScanningRadar={isScanningGmail}
      />

      {/* MAIN MONOLITH COMMAND SURFACE */}
      <div className="flex-1 flex flex-col justify-between min-w-0 overflow-x-hidden">
        {/* 1. MONOLITHIC HEADER */}
        <header className="relative z-10 border-b border-[#231e19] bg-[#0d0b09]/95 backdrop-blur-md px-6 lg:px-12 py-5">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Monolith Wordmark & Autonomous Indicator (DUNE MINIMALIST text removed) */}
            <div className="flex items-center gap-4">
              <div className="w-9 h-9 rounded-none border border-[#b87326]/60 bg-[#171410] flex items-center justify-center shadow-lg">
                <span className="text-base text-[#d48b38] font-black">▲</span>
              </div>
              <div>
                <div className="flex items-center gap-3">
                  <h1 className="text-sm lg:text-base font-black tracking-[0.3em] uppercase text-[#ede6dc]">
                    THE MONOLITH
                  </h1>
                  <span className="inline-flex items-center gap-1.5 px-2 py-0.5 border border-[#b87326]/40 text-[#d48b38] bg-[#b87326]/10 text-[9px] tracking-[0.15em] font-extrabold uppercase">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#d48b38] animate-pulse" />
                    AUTONOMOUS ENGINE ACTIVE
                  </span>
                </div>
                <p className="text-[10px] tracking-[0.2em] text-[#9c9183] mt-0.5 uppercase">
                  PURE EFFICIENCY &amp; CALM // {totalAssimilated.toLocaleString()} SIGNALS ASSIMILATED
                </p>
              </div>
            </div>

            {/* Controls: 3-Way Mode Switcher & Actions */}
            <div className="flex items-center gap-3">
              {/* 3-Way Mode Switcher */}
              <div className="inline-flex p-1 border border-[#2d2720] bg-[#120f0d] text-[10px] tracking-[0.15em] font-bold">
                <button
                  type="button"
                  onClick={() => onSwitchMode && onSwitchMode('monolith')}
                  className={`px-3 py-1 cursor-pointer transition-colors ${
                    activeTab === 'prime'
                      ? 'bg-[#2b241c] text-[#d48b38] border border-[#b87326]/40 shadow-xs'
                      : 'text-[#8c8275] hover:text-[#ede6dc]'
                  }`}
                  title="Monolithic Focus"
                >
                  ▲ MONOLITH
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setActiveTab('autopilot');
                    if (onSwitchMode) onSwitchMode('zen');
                  }}
                  className={`px-3 py-1 cursor-pointer transition-colors ${
                    activeTab === 'autopilot'
                      ? 'bg-[#2b241c] text-[#d48b38] border border-[#b87326]/40 shadow-xs'
                      : 'text-[#8c8275] hover:text-[#ede6dc]'
                  }`}
                  title="Autonomous Zen Deck"
                >
                  🌿 ZEN
                </button>
                <button
                  type="button"
                  onClick={() => onSwitchMode && onSwitchMode('studio')}
                  className="px-3 py-1 text-[#8c8275] hover:text-[#ede6dc] transition-colors cursor-pointer"
                  title="Switch to Full Studio Mode"
                >
                  🎛️ STUDIO
                </button>
              </div>

              {/* Batch Dispatch Action */}
              {onOpenBatchApply && (
                <button
                  type="button"
                  onClick={onOpenBatchApply}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#b87326]/60 hover:border-[#d48b38] bg-[#1a1612] text-[#d48b38] hover:text-[#ede6dc] text-[10px] tracking-[0.15em] font-black transition-all cursor-pointer shadow-xs"
                  title="Dispatch 1-Click Batch Automated Applications"
                >
                  <Zap size={11} className="text-[#d48b38]" />
                  <span>BATCH DISPATCH</span>
                </button>
              )}

              {/* Profile Action */}
              <button
                type="button"
                onClick={onOpenProfileModal}
                className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#2d2720] hover:border-[#b87326]/50 bg-[#120f0d] hover:bg-[#1a1612] text-[#c4b9aa] hover:text-white text-[10px] tracking-[0.15em] font-bold transition-all cursor-pointer"
              >
                <Compass size={12} className="text-[#d48b38]" />
                <span>{profile?.name ? profile.name.toUpperCase() : 'PROFILE'}</span>
              </button>
            </div>
          </div>
        </header>

        {/* Global Notification Banner */}
        {notificationMsg && (
          <div className="bg-[#171410] border-b border-[#b87326]/40 text-[#d48b38] px-6 py-2.5 text-xs tracking-wider flex items-center justify-between font-mono animate-in fade-in duration-200">
            <span className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[#d48b38] animate-ping" />
              {notificationMsg}
            </span>
            <button
              onClick={() => setNotificationMsg(null)}
              className="text-[#8c8275] hover:text-white text-xs font-bold cursor-pointer"
            >
              ✕
            </button>
          </div>
        )}

        {/* 2. THE MONOLITH COMMAND SURFACE BODY */}
        <main className="relative z-10 max-w-7xl mx-auto px-6 lg:px-12 py-10 w-full space-y-12 flex-1">
          {/* TAB 1: PRIME MONOLITH VIEW */}
          {activeTab === 'prime' && (
            <div className="space-y-12 animate-in fade-in duration-300">
              {/* PRIME MONOLITH CARD (THE SINGLE HIGHEST-IMPACT TRAJECTORY) */}
              {primeJob ? (
                <section className="space-y-3">
                  <div className="flex items-center justify-between text-[11px] tracking-[0.25em] text-[#8c8275] uppercase">
                    <span className="flex items-center gap-2 font-bold">
                      <Target size={13} className="text-[#d48b38]" />
                      PRIME TRAJECTORY // HIGHEST STRATEGIC CONVERGENCE
                    </span>
                    <span className="text-[#d48b38] font-black">
                      RANK #01
                    </span>
                  </div>

                  <motion.div 
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                    className="bg-[#12100d] border border-[#2e271f] hover:border-[#b87326]/60 transition-all duration-500 p-7 lg:p-10 relative overflow-hidden shadow-2xl group"
                  >
                    {/* Corner Architectural Accent */}
                    <div className="absolute top-0 right-0 w-16 h-16 pointer-events-none border-t border-r border-[#b87326]/40" />

                    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8">
                      {/* Left Side: Massive Monolithic Details */}
                      <div className="space-y-4 max-w-3xl">
                        <div className="flex flex-wrap items-center gap-3 text-[10px] tracking-[0.2em] uppercase font-bold">
                          <span className="px-2 py-0.5 bg-[#b87326]/20 border border-[#b87326]/40 text-[#d48b38]">
                            {primeJob.stream || 'CORE ENTERPRISE SYSTEMS'}
                          </span>
                          <span className="px-2 py-0.5 bg-[#1a1713] border border-[#332b22] text-[#a89d8e]">
                            {primeJob.score || 95}% ALIGNMENT
                          </span>
                          <span className="text-[#8c8275] flex items-center gap-1">
                            <Clock size={11} className="text-[#b87326]" />
                            {formatJobPostedAge(primeJob.date)}
                          </span>
                        </div>

                        <div>
                          <h2 className="text-2xl lg:text-4xl font-black tracking-wider uppercase text-[#ede6dc] leading-tight group-hover:text-white transition-colors">
                            {primeJob.title}
                          </h2>
                          <p className="text-base lg:text-xl font-bold tracking-widest text-[#d48b38] mt-1 uppercase">
                            {primeJob.company}
                          </p>
                        </div>

                        <p className="text-xs lg:text-sm text-[#a89d8e] leading-relaxed line-clamp-3 font-sans font-medium">
                          {primeJob.description || 'Deep architectural alignment with your target skill vector. Commute constraints, compensation thresholds, and semantic keywords verified nominal.'}
                        </p>

                        <div className="flex flex-wrap items-center gap-6 text-xs text-[#c4b9aa] pt-2 border-t border-[#231e19]">
                          <span className="flex items-center gap-1.5 tracking-wider">
                            <MapPin size={13} className="text-[#d48b38]" />
                            {primeJob.location || 'Melbourne VIC'}
                          </span>
                          <span className="flex items-center gap-1.5 tracking-wider font-bold text-[#ede6dc]">
                            <DollarSign size={13} className="text-[#d48b38]" />
                            {primeJob.salary || 'Competitive Sovereign Comp'}
                          </span>
                        </div>

                        {/* Fast Zen Automation Actions */}
                        <div className="flex flex-wrap items-center gap-3 pt-2">
                          <button
                            type="button"
                            onClick={() => handleQuickPreviewDocs(primeJob)}
                            className="text-[10px] tracking-[0.15em] font-bold text-[#d48b38] hover:text-white flex items-center gap-1.5 border border-[#2e271f] hover:border-[#b87326]/50 bg-[#171410] px-3 py-1.5 transition-colors cursor-pointer"
                          >
                            <FileText size={12} className="text-[#d48b38]" />
                            <span>TAILORED DOCS</span>
                          </button>
                          <button
                            type="button"
                            onClick={() => handleQuickPreviewPsych(primeJob)}
                            className="text-[10px] tracking-[0.15em] font-bold text-[#a89d8e] hover:text-white flex items-center gap-1.5 border border-[#2e271f] hover:border-[#b87326]/50 bg-[#171410] px-3 py-1.5 transition-colors cursor-pointer"
                          >
                            <BrainCircuit size={12} className="text-[#b87326]" />
                            <span>FIT AUDIT</span>
                          </button>
                          <button
                            type="button"
                            onClick={() => handleMarkApplied(primeJob)}
                            className="text-[10px] tracking-[0.15em] font-bold text-[#8c8275] hover:text-emerald-400 flex items-center gap-1.5 border border-[#2e271f] hover:border-emerald-700/50 bg-[#171410] px-3 py-1.5 transition-colors cursor-pointer"
                          >
                            <CheckCircle2 size={12} />
                            <span>MARK APPLIED</span>
                          </button>
                        </div>
                      </div>

                      {/* Right Side: Heavy Action Buttons */}
                      <div className="flex flex-col sm:flex-row lg:flex-col gap-3 min-w-[240px] shrink-0">
                        <button
                          type="button"
                          onClick={() => onOpenGenerator && onOpenGenerator(primeJob)}
                          className="w-full py-4 px-6 bg-[#b87326] hover:bg-[#d48b38] text-black font-black text-xs tracking-[0.25em] uppercase transition-all duration-300 shadow-xl flex items-center justify-center gap-2 cursor-pointer border border-[#d48b38]"
                        >
                          <span>PREPARE APPLICATION</span>
                          <ArrowUpRight size={16} className="shrink-0 stroke-[3]" />
                        </button>

                        <button
                          type="button"
                          onClick={() => onOpenJobModal && onOpenJobModal(primeJob)}
                          className="w-full py-3.5 px-6 bg-[#171411] hover:bg-[#211d18] text-[#c4b9aa] hover:text-white font-bold text-xs tracking-[0.2em] uppercase transition-all duration-300 border border-[#2e271f] hover:border-[#b87326]/50 flex items-center justify-center gap-2 cursor-pointer"
                        >
                          <span>INSPECT INTELLIGENCE</span>
                          <ChevronRight size={14} className="text-[#8c8275]" />
                        </button>
                      </div>
                    </div>
                  </motion.div>
                </section>
              ) : (
                <div className="p-12 text-center border border-[#27211a] bg-[#120f0d] space-y-3">
                  <p className="text-sm tracking-[0.2em] text-[#a89d8e]">NO RECENT VECTORS DETECTED</p>
                  <p className="text-xs text-[#706659]">Background engine is assimilating new listings. All systems nominal.</p>
                </div>
              )}

              {/* 3. CURATED SECONDARY MONOLITH SLABS */}
              {secondarySlabs.length > 0 && (
                <section className="space-y-4">
                  <div className="flex items-center justify-between text-[11px] tracking-[0.25em] text-[#8c8275] uppercase">
                    <span className="flex items-center gap-2 font-bold">
                      <Compass size={13} className="text-[#d48b38]" />
                      SECONDARY MONOLITHS // FILTERED ESSENCE
                    </span>
                    <span className="text-[10px] text-[#706659]">
                      {secondarySlabs.length} OF {activeJobs.length} VERIFIED
                    </span>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6">
                    {secondarySlabs.map((job, idx) => (
                      <motion.div
                        key={job.id || `${job.company}_${job.title}_${idx}`}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5, delay: idx * 0.08 }}
                        onClick={() => onOpenJobModal && onOpenJobModal(job)}
                        className="bg-[#12100d] border border-[#27211a] hover:border-[#b87326]/60 p-6 space-y-4 transition-all duration-400 cursor-pointer group relative shadow-lg"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="space-y-1">
                            <span className="text-[9px] tracking-[0.25em] text-[#d48b38] uppercase font-bold">
                              VECTOR #{String(idx + 2).padStart(2, '0')} · {job.score || 85}% FIT
                            </span>
                            <h3 className="text-base font-black tracking-wide uppercase text-[#ede6dc] group-hover:text-white transition-colors leading-snug line-clamp-1">
                              {job.title}
                            </h3>
                            <p className="text-xs tracking-wider font-bold text-[#a89d8e] uppercase line-clamp-1">
                              {job.company}
                            </p>
                          </div>

                          <span className="text-[9px] tracking-wider text-[#8c8275] border border-[#2e271f] px-1.5 py-0.5 shrink-0">
                            {formatJobPostedAge(job.date)}
                          </span>
                        </div>

                        <div className="flex items-center justify-between text-xs pt-3 border-t border-[#1f1b16] text-[#8c8275]">
                          <span className="truncate max-w-[160px] text-[11px]">
                            <MapPin size={11} className="inline mr-1 text-[#b87326]" />
                            {job.location}
                          </span>
                          <div className="flex items-center gap-2">
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleQuickPreviewDocs(job);
                              }}
                              className="text-[10px] tracking-wider text-[#8c8275] hover:text-[#d48b38] p-1 cursor-pointer"
                              title="Preview Tailored Documents"
                            >
                              <FileText size={13} />
                            </button>
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                onOpenGenerator && onOpenGenerator(job);
                              }}
                              className="text-[10px] tracking-[0.2em] font-black uppercase text-[#d48b38] hover:text-white flex items-center gap-1 border border-[#b87326]/30 bg-[#b87326]/10 hover:bg-[#b87326]/20 px-2.5 py-1 transition-colors"
                            >
                              <span>PREP</span>
                              <ArrowUpRight size={12} />
                            </button>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </section>
              )}
            </div>
          )}

          {/* TAB 2: AUTONOMOUS ACTION DECK (ZEN AUTOMATION IN MONOLITH THEME) */}
          {activeTab === 'autopilot' && (
            <div className="space-y-8 animate-in fade-in duration-300">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#231e19] pb-4">
                <div>
                  <h2 className="text-lg font-black tracking-[0.2em] text-[#ede6dc] uppercase flex items-center gap-2">
                    <Zap size={16} className="text-[#d48b38]" />
                    AUTONOMOUS ACTION DECK
                  </h2>
                  <p className="text-xs text-[#8c8275] tracking-wider mt-1">
                    Prepared packages ready for immediate 1-click execution or review.
                  </p>
                </div>
                {onOpenBatchApply && (
                  <button
                    type="button"
                    onClick={onOpenBatchApply}
                    className="py-2 px-4 bg-[#b87326] hover:bg-[#d48b38] text-black font-black text-[11px] tracking-[0.2em] uppercase transition-all shadow-md flex items-center gap-2 cursor-pointer self-start sm:self-auto"
                  >
                    <Send size={13} />
                    <span>DISPATCH ALL READY</span>
                  </button>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6">
                {actionDeck.map((job, idx) => (
                  <div
                    key={job.id || `${job.company}_${job.title}_${idx}`}
                    className="bg-[#12100d] border border-[#28221b] hover:border-[#b87326]/60 p-6 space-y-4 transition-all duration-300 relative shadow-xl group"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="flex items-center gap-2 text-[9px] tracking-widest text-[#d48b38] uppercase font-bold">
                          <span>READY TARGET #{String(idx + 1).padStart(2, '0')}</span>
                          <span>•</span>
                          <span>{job.score || 88}% MATCH</span>
                        </div>
                        <h3 className="text-base font-black tracking-wide text-[#ede6dc] group-hover:text-white uppercase mt-1 line-clamp-1">
                          {job.title}
                        </h3>
                        <p className="text-xs text-[#a89d8e] font-bold uppercase tracking-wider">
                          {job.company}
                        </p>
                      </div>
                      <span className="text-[9px] font-mono text-[#706659] border border-[#262019] px-2 py-0.5">
                        {formatJobPostedAge(job.date)}
                      </span>
                    </div>

                    <p className="text-xs text-[#8c8275] font-sans line-clamp-2">
                      {job.description || 'Target opportunity verified by background autonomous engine. Custom resume and cover letter synthesized.'}
                    </p>

                    <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-[#1f1b16]">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleQuickPreviewDocs(job)}
                          className="text-[10px] tracking-wider font-bold text-[#d48b38] hover:text-white flex items-center gap-1 border border-[#2e271f] bg-[#16130f] px-2.5 py-1 transition-colors cursor-pointer"
                        >
                          <FileText size={11} />
                          <span>PREVIEW DOCS</span>
                        </button>
                        <button
                          type="button"
                          onClick={() => handleQuickPreviewPsych(job)}
                          className="text-[10px] tracking-wider font-bold text-[#8c8275] hover:text-[#ede6dc] flex items-center gap-1 border border-[#2e271f] bg-[#16130f] px-2.5 py-1 transition-colors cursor-pointer"
                        >
                          <BrainCircuit size={11} />
                          <span>AUDIT</span>
                        </button>
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleMarkApplied(job)}
                          className="text-[10px] tracking-wider text-[#706659] hover:text-emerald-400 p-1 cursor-pointer"
                          title="Mark as Applied"
                        >
                          <CheckCircle2 size={15} />
                        </button>
                        <button
                          type="button"
                          onClick={() => onOpenGenerator && onOpenGenerator(job)}
                          className="text-[10px] tracking-[0.2em] font-black uppercase text-[#d48b38] hover:text-black hover:bg-[#d48b38] flex items-center gap-1 border border-[#b87326]/50 bg-[#b87326]/10 px-3 py-1.5 transition-all cursor-pointer"
                        >
                          <span>DISPATCH</span>
                          <ArrowUpRight size={12} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: ALIEN RADAR & TELEMETRY STREAM */}
          {activeTab === 'radar' && (
            <div className="space-y-8 animate-in fade-in duration-300">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#231e19] pb-4">
                <div>
                  <h2 className="text-lg font-black tracking-[0.2em] text-[#ede6dc] uppercase flex items-center gap-2">
                    <Activity size={16} className="text-[#d48b38]" />
                    ALIEN RADAR &amp; TELEMETRY MATRIX
                  </h2>
                  <p className="text-xs text-[#8c8275] tracking-wider mt-1">
                    Continuous autonomous background observation, recruiter synchronization &amp; signal assimilation.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleTriggerGmailScan}
                  disabled={isScanningGmail}
                  className="py-2 px-4 bg-[#1a1612] hover:bg-[#262019] text-[#d48b38] border border-[#b87326]/60 font-bold text-[11px] tracking-[0.15em] uppercase transition-all shadow-xs flex items-center gap-2 cursor-pointer disabled:opacity-50"
                >
                  <RefreshCw size={13} className={isScanningGmail ? 'animate-spin' : ''} />
                  <span>{isScanningGmail ? 'RADAR ACTIVE...' : 'TRIGGER GMAIL RADAR'}</span>
                </button>
              </div>

              {/* Autopilot Counters */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                <div className="bg-[#12100d] border border-[#27211a] p-5 space-y-1">
                  <span className="text-[10px] tracking-widest text-[#8c8275] uppercase font-bold">Resumes Synthesized</span>
                  <p className="text-2xl font-black text-[#d48b38]">{agentState.stats.resumesSynthesized || actionDeck.length}</p>
                </div>
                <div className="bg-[#12100d] border border-[#27211a] p-5 space-y-1">
                  <span className="text-[10px] tracking-widest text-[#8c8275] uppercase font-bold">Cover Letters</span>
                  <p className="text-2xl font-black text-[#d48b38]">{agentState.stats.coverLettersSynthesized || actionDeck.length}</p>
                </div>
                <div className="bg-[#12100d] border border-[#27211a] p-5 space-y-1">
                  <span className="text-[10px] tracking-widest text-[#8c8275] uppercase font-bold">Psychology Audits</span>
                  <p className="text-2xl font-black text-[#d48b38]">{agentState.stats.psychProfilesBaked || Math.round(actionDeck.length * 0.8)}</p>
                </div>
                <div className="bg-[#12100d] border border-[#27211a] p-5 space-y-1">
                  <span className="text-[10px] tracking-widest text-[#8c8275] uppercase font-bold">Applications Tracked</span>
                  <p className="text-2xl font-black text-emerald-400">{applications.length}</p>
                </div>
              </div>

              {/* Activity Log Stream */}
              <div className="bg-[#100e0b] border border-[#231e19] p-6 space-y-4">
                <h3 className="text-xs font-bold tracking-[0.2em] text-[#c4b9aa] uppercase flex items-center gap-2">
                  <Terminal size={14} className="text-[#d48b38]" />
                  <span>AUTONOMOUS ENGINE LOG STREAM</span>
                </h3>
                <div className="space-y-2 max-h-72 overflow-y-auto font-mono text-xs text-[#8c8275]">
                  {agentState.activityLog && agentState.activityLog.length > 0 ? (
                    agentState.activityLog.map((log, i) => (
                      <div key={i} className="flex items-start gap-2 py-1 border-b border-[#181410]">
                        <span className="text-[#b87326] shrink-0">[{log.time || 'NOW'}]</span>
                        <span className="text-[#c4b9aa]">{log.msg}</span>
                      </div>
                    ))
                  ) : (
                    <div className="space-y-1 text-[#706659]">
                      <p>[SYSTEM] All autonomous agents synchronized with live gateway.</p>
                      <p>[SYSTEM] Listening for new recruiter responses on Gmail thread tracker.</p>
                      <p>[SYSTEM] Auto-screening 6,106 opportunities against active candidate profile.</p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </main>

        {/* 3. SILENT PULSE TELEMETRY BAR (BOTTOM STATUS) */}
        <footer className="relative z-10 border-t border-[#231e19] bg-[#0c0a08] px-6 lg:px-12 py-3 text-[10px] tracking-[0.2em] text-[#706659] uppercase">
          <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="flex items-center gap-4 truncate">
              <span className="flex items-center gap-1.5 text-[#d48b38] font-bold shrink-0">
                <Activity size={12} className="animate-pulse" />
                <span>SYSTEM NOMINAL</span>
              </span>
              <span className="text-[#332b22]">/</span>
              <span className="text-[#a89d8e] truncate">
                {totalAssimilated.toLocaleString()} SIGNALS ASSIMILATED
              </span>
              <span className="text-[#332b22] hidden md:inline">/</span>
              <span className="text-[#8c8275] hidden md:inline">
                AUTONOMOUS SCREENING &amp; SCORING ACTIVE
              </span>
            </div>

            <div className="flex items-center gap-4 text-[#8c8275] shrink-0">
              <span>APPLICATIONS DEPLOYED: {applications.length}</span>
              <span className="text-[#332b22]">/</span>
              <button
                type="button"
                onClick={onOpenCommandPalette}
                className="text-[#c4b9aa] hover:text-[#d48b38] transition-colors cursor-pointer"
              >
                COMMAND [⌘K]
              </button>
            </div>
          </div>
        </footer>
      </div>

      {/* QUICK DOCUMENT & PSYCHOLOGY MODAL (MONOLITH STONE STYLING) */}
      <AnimatePresence>
        {activeModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-150">
            <div className="bg-[#12100d] border border-[#b87326]/50 max-w-2xl w-full p-6 space-y-6 shadow-2xl relative font-mono">
              <div className="flex items-start justify-between border-b border-[#262019] pb-3">
                <div>
                  <span className="text-[9px] tracking-widest text-[#d48b38] uppercase font-bold">
                    {activeModal.type === 'doc' ? 'AUTONOMOUS DOCUMENT ARTIFACT' : 'PSYCHOLOGY & CULTURE DECODER'}
                  </span>
                  <h3 className="text-base font-black text-[#ede6dc] uppercase mt-0.5">
                    {activeModal.job.title} — {activeModal.job.company}
                  </h3>
                </div>
                <button
                  onClick={() => setActiveModal(null)}
                  className="text-[#8c8275] hover:text-white text-base cursor-pointer p-1"
                >
                  ✕
                </button>
              </div>

              {activeModal.type === 'doc' ? (
                <div className="space-y-4 text-xs">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-[11px] text-[#a89d8e]">
                      <span className="font-bold text-[#d48b38]">TAILORED RESUME</span>
                      <button
                        type="button"
                        onClick={() => handleCopyText(activeModal.resume, 'resume')}
                        className="flex items-center gap-1 hover:text-white cursor-pointer"
                      >
                        {copiedKey === 'resume' ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                        <span>{copiedKey === 'resume' ? 'COPIED' : 'COPY'}</span>
                      </button>
                    </div>
                    <pre className="p-3 bg-[#0d0b09] border border-[#231e19] text-[#c4b9aa] whitespace-pre-wrap font-sans text-xs max-h-40 overflow-y-auto">
                      {activeModal.resume}
                    </pre>
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-[11px] text-[#a89d8e]">
                      <span className="font-bold text-[#d48b38]">BESPOKE COVER LETTER</span>
                      <button
                        type="button"
                        onClick={() => handleCopyText(activeModal.coverLetter, 'cover')}
                        className="flex items-center gap-1 hover:text-white cursor-pointer"
                      >
                        {copiedKey === 'cover' ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                        <span>{copiedKey === 'cover' ? 'COPIED' : 'COPY'}</span>
                      </button>
                    </div>
                    <pre className="p-3 bg-[#0d0b09] border border-[#231e19] text-[#c4b9aa] whitespace-pre-wrap font-sans text-xs max-h-40 overflow-y-auto">
                      {activeModal.coverLetter}
                    </pre>
                  </div>
                </div>
              ) : (
                <div className="space-y-3 text-xs">
                  <span className="font-bold text-[#d48b38]">ORGANIZATIONAL PSYCHOLOGY</span>
                  <div className="p-4 bg-[#0d0b09] border border-[#231e19] text-[#c4b9aa] font-sans leading-relaxed">
                    {typeof activeModal.insights?.companyCulture === 'string'
                      ? activeModal.insights.companyCulture
                      : JSON.stringify(activeModal.insights, null, 2)}
                  </div>
                </div>
              )}

              <div className="flex items-center justify-end gap-3 pt-3 border-t border-[#231e19]">
                <button
                  type="button"
                  onClick={() => {
                    setActiveModal(null);
                    if (onOpenGenerator) onOpenGenerator(activeModal.job);
                  }}
                  className="py-2.5 px-5 bg-[#b87326] hover:bg-[#d48b38] text-black font-black text-xs tracking-wider uppercase transition-colors cursor-pointer"
                >
                  OPEN IN GENERATOR
                </button>
              </div>
            </div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
