from .sources import SearchQuery

DEFAULT_QUERIES = (
    SearchQuery("systems administrator"),
    SearchQuery("support engineer"),
    SearchQuery("helpdesk"),
    SearchQuery("level 3 support"),
    SearchQuery("level 2 support"),
    SearchQuery("level 1 support"),
    SearchQuery("infrastructure engineer"),
    SearchQuery("cloud engineer"),
    SearchQuery("devops engineer"),
    SearchQuery("service desk analyst"),
    SearchQuery("microsoft 365"),
    SearchQuery("azure"),
    SearchQuery("casual work", stream="bridge"),
    SearchQuery("warehouse", stream="bridge"),
    SearchQuery("traineeship", stream="traineeship"),
    SearchQuery("data centre technician", stream="traineeship"),
    SearchQuery("cabling technician", stream="traineeship"),
    # Closely related roles based on the candidate's M365, endpoint, identity,
    # automation, and service-management experience.
    SearchQuery("Microsoft 365 Administrator"),
    SearchQuery("SharePoint Administrator"),
    SearchQuery("SharePoint Developer"),
    SearchQuery("Azure Administrator"),
    SearchQuery("Entra ID Administrator"),
    SearchQuery("Intune Administrator"),
    SearchQuery("Endpoint Engineer"),
    SearchQuery("Identity and Access Administrator"),
    SearchQuery("PowerShell Automation Engineer"),
    SearchQuery("ServiceNow Administrator"),
    SearchQuery("Technical Support Engineer"),
    SearchQuery("Infrastructure Consultant"),
)
